# --- !Ups

CREATE TABLE users (
    id long PRIMARY KEY,
    username text,
    name text,
    lastName text,
    email text,
    phone text,
    activated bool,
    confirmed bool,
    password text);

CREATE TABLE activations(
    userId long PRIMARY KEY,
    secret text);


create table "RENT" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"userId" BIGINT NOT NULL, "flatId" BIGINT NOT NULL,"from" TIMESTAMP NOT NULL,"till" TIMESTAMP,"confirmed" BOOLEAN NOT NULL);

# --- !Downs

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS activations;

drop table "RENT";
